---
- name: Provision
  hosts: personal
  vars_files:
    - ./variables.yaml
  tasks:
    - name: Update package registry
      ansible.builtin.apt:
        upgrade: dist

    - name: Install base dependencies
      ansible.builtin.apt:
        pkg:
          - curl
          - git
          - dbus-user-session
          - docker.io
          - zsh
          - ripgrep
          - fd-find
          - tmux

    - name: Disable and mask Docker daemon
      ansible.builtin.systemd_service:
        name: docker
        enabled: false
        masked: true

    - name: Ensure user group 1000 exists
      ansible.builtin.group:
        name: "{{ user.name }}"
        state: present
        gid: 1000

    - name: Create user "{{ user.name }}", set group id and add to relevant groups
      ansible.builtin.user:
        name: "{{ user.name }}"
        password: "{{ user.password | password_hash('sha512', user.salt) }}"
        append: true
        uid: 1000
        group: 1000
        groups:
          - sudo
          - docker
        shell: /bin/zsh

    - name: Configure user environment
      block:
        - name: Create user directories
          ansible.builtin.file:
            path: "$HOME/{{ item }}"
            state: directory
            mode: 0700
          loop:
            - .ssh/
            - .config/
            - .local/bin/
            - .local/
            - .local/share/
            - .local/state/

        - name: Allow SSH access for user "{{ user.name }}"
          ansible.posix.authorized_key:
            user: "{{ user.name }}"
            state: present
            key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/' + ssh_key) }}"

        - name: Download Oh My Zsh
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
            dest: "$HOME/oh-my-zsh-install.sh"
            mode: 0700

        - name: Install Oh My Zsh
          ansible.builtin.command: ./oh-my-zsh-install.sh --unattended
          args:
            chdir: "$HOME"
            creates: "$HOME/.oh-my-zsh/"

        - name: Install Asdf. The tool version manager
          ansible.builtin.git:
            repo: https://github.com/asdf-vm/asdf.git
            dest: "$HOME/.asdf"

        - name: Pull dotfiles repository
          ansible.builtin.git:
            repo: https://github.com/99linesofcode/dotfiles.git
            dest: "$HOME/dotfiles"
            single_branch: yes
            version: main

        - name: Install Neovim through Asdf
          ansible.builtin.shell: |
            export ASDF_DIR="$HOME/.asdf"
            . $HOME/.asdf/asdf.sh
            asdf plugin add neovim
            asdf install neovim stable
            asdf global neovim stable

        - name: Clean up installation artifacts and other unused files
          ansible.builtin.file:
            path: "$HOME/{{ item }}"
            state: absent
          loop:
            - .bash_logout
            - .bashrc
            - .profile
            - .zshrc
            - oh-my-zsh-install.sh

        - name: Create the relevant symbolic links
          ansible.builtin.shell: "ln -sfn {{ item.src }} {{ item.dest }}"
          loop:
            - { src: "$HOME/dotfiles/.zshrc", dest: "$HOME/.zshrc" }
            - { src: "$HOME/dotfiles/.config/nvim", dest: "$HOME/.config/nvim" }
            - { src: "$(which nvim)", dest: "$HOME/.local/bin/vi" }

        - name: Remove keychain plugin and identity loading configuration from .zshrc
          ansible.builtin.lineinfile:
            path: "$HOME/.zshrc"
            regexp: "{{ item }}"
            state: absent
          loop:
            - "gpg-agent$"
            - "^zstyle :omz:plugins:keychain agents gpg,ssh"
            - "^zstyle :omz:plugins:keychain identities .*"
      become: true
      become_user: "{{ user.name }}"

      # - name: Remove root SSH access
      #   ansible.posix.authorized_key:
      #     user: root
      #     state: absent
      #     key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/' + ssh_key) }}"
