---
name: Provision
hosts: personal
tasks:
  - name: Update package registry
    ansible.builtin.apt:
      upgrade: dist

  - name: Install base dependencies
    ansible.builtin.apt:
      pkg:
        - curl
        - git
        - dbus-user-session
        - docker.io
        - zsh
        - ripgrep
        - fd-find
        - tmux

  - name: Ensure user group 1000 exists
    ansible.builtin.group:
      name: jordy
      state: present
      gid: 1000

  - name: Add user 'jordy' and add it to group 1000
    ansible.builtin.user:
      name: jordy
      uid: 1000
      group: 1000
      shell: /bin/zsh

  - name: Create user directories
    ansible.builtin.file:
      path: "/home/jordy/{{ item }}"
      state: directory
      owner: jordy
      group: jordy
      mode: 0700
      loop:
        - .ssh/
        - .config/
        - .local/
        - .local/bin/
        - .local/share/
        - .local/state/
        - scripts/

  - name: Copy authorized_keys SSH keys to jordy user
    ansible.builtin.copy:
      src: /root/.ssh/authorized_keys
      dest: /home/jordy/.ssh/authorized_keys
      remote_src: true
      owner: jordy
      group: jordy
      mode: 0600

  - name: Disable and mask Docker daemon
    ansible.builtin.systemd_service:
      name: docker
      enabled: false
      masked: true

  - name: Add 'jordy' user to groups
    ansible.builtin.user:
      name: jordy
      groups:
        - sudo
        - docker
      append: true

  - name: Download oh-my-zsh
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: /home/jordy/oh-my-zsh-install.sh
      owner: jordy
      group: jordy
      mode: 0700

  - name: Install oh-my-zsh
    ansible.builtin.command: ./oh-my-zsh-install.sh --unattended
    become: yes
    become_user: jordy
    args:
      chdir: /home/jordy/
      creates: /home/jordy/.oh-my-zsh/

  - name: Clean up installation artifacts
    ansible.builtin.file:
      path: "/home/jordy/{{ item }}"
      state: absent
    loop:
      - oh-my-zsh-install.sh
      - .zshrc

  # TODO figure out how to change file ownership
  # TODO clone Asdf
  # TODO install latest version of neovim

  - name: Clone dotfiles repository
    ansible.builtin.git:
      repo: https://github.com/99linesofcode/dotfiles.git
      dest: /home/jordy/dotfiles
      single_branch: yes
      version: main

  - name: Symlink relevant dotfiles
    ansible.builtin.file:
      src: "/home/jordy/dotfiles/{{ item }}"
      dest: "/home/jordy/{{ item }}"
      owner: jordy
      group: jordy
      state: link
    loop:
      - .zshrc
      - .config/nvim

  # TODO remove ssh-agent and ssh-agent identity loading

  - name: Disable root SSH access
    ansible.builtin.file:
      path: "/root/.ssh/authorized_keys"
      state: absent
