---
- name: Provision
  hosts: personal
  vars_files:
    - ./variables.yaml
  tasks:
    - name: Update package registry
      ansible.builtin.apt:
        upgrade: dist

    - name: Install base dependencies
      ansible.builtin.apt:
        pkg:
          - curl
          - git
          - dbus-user-session
          - docker.io
          - zsh
          - ripgrep
          - fd-find
          - tmux

    - name: Disable and mask Docker daemon
      ansible.builtin.systemd_service:
        name: docker
        enabled: false
        masked: true

    - name: Ensure user group 1000 exists
      ansible.builtin.group:
        name: jordy
        state: present
        gid: 1000

    - name: Add user 'jordy' and add it to group 1000
      ansible.builtin.user:
        name: jordy
        password: "{{ user.password | password_hash('sha512', user.salt) }}"
        uid: 1000
        group: 1000
        shell: /bin/zsh

    - name: configure user environment
      block:
        - name: Create user directories
          ansible.builtin.file:
            path: "/home/jordy/{{ item }}"
            state: directory
            mode: 0700
          loop:
            - .ssh/
            - .config/
            - .local/bin/
            - .local/
            - .local/share/
            - .local/state/
            - scripts/

        - name: Allow SSH access for user jordy
          ansible.posix.authorized_key:
            user: jordy
            state: present
            key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/blade_strato_ed25519.pub')}}"

        - name: Add 'jordy' user to groups
          ansible.builtin.user:
            name: jordy
            groups:
              - sudo
              - docker
            append: true

        - name: Download oh-my-zsh
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
            dest: /home/jordy/oh-my-zsh-install.sh
            mode: 0700

        - name: Install oh-my-zsh
          ansible.builtin.command: ./oh-my-zsh-install.sh --unattended
          args:
            chdir: /home/jordy/
            creates: /home/jordy/.oh-my-zsh/

        - name: Clean up installation artifacts
          ansible.builtin.file:
            path: "/home/jordy/{{ item }}"
            state: absent
          loop:
            - oh-my-zsh-install.sh
            - .zshrc

        # TODO perform everything as jordy to simplify setting file ownership
        # TODO clone Asdf
        # TODO install latest version of neovim

        - name: Clone dotfiles repository
          ansible.builtin.git:
            repo: https://github.com/99linesofcode/dotfiles.git
            dest: /home/jordy/dotfiles
            single_branch: yes
            version: main

        - name: Symlink relevant dotfiles
          ansible.builtin.file:
            src: "/home/jordy/dotfiles/{{ item }}"
            dest: "/home/jordy/{{ item }}"
            state: link
          loop:
            - .zshrc
            - .config/nvim

        # TODO remove ssh-agent and ssh-agent identity loading

        # - name: Remove root SSH access
        #   ansible.posix.authorized_key:
        #     user: root
        #     state: absent
        #     key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/blade_strato_ed25519.pub')}}"
      become: true
      become_user: jordy
